"""SQLAlchemy models representing the database schema for SteelWorks.

Each class corresponds to a table defined in db/schema.sql. Using SQLAlchemy's
ORM makes it easy to interact with the database in a Pythonic way while still
allowing us to write expressive queries in the repository layer.

Time complexity notes: Instantiating models is O(1). Query operations on the
session are delegated to the database; complexity depends on SQL and indexes.
"""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    ForeignKey,
    Integer,
    String,
    Table,
    Time,
    UniqueConstraint,
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class Lot(Base):
    """Manufacturing lot / batch identifier.

    Attributes
    ----------
    id: int
        Surrogate primary key (autogenerated).
    lot: str
        Business key that may be inconsistently formatted across sources.

    Relationships
    -------------
    production_records: list[ProductionRecord]
    inspection_records: list[InspectionRecord]
    shipping_records: list[ShippingRecord]
    """

    __tablename__ = "lots"

    id = Column(BigInteger, primary_key=True)
    lot = Column(String, nullable=False, unique=True)

    production_records = relationship("ProductionRecord", back_populates="lot")
    inspection_records = relationship("InspectionRecord", back_populates="lot")
    shipping_records = relationship("ShippingRecord", back_populates="lot")


class ProductionLine(Base):
    """Represents a production line used for filtering and grouping.

    Attributes
    ----------
    id: int
    line: str

    Relationships
    -------------
    production_records: list[ProductionRecord]
    inspection_records: list[InspectionRecord]
    """

    __tablename__ = "production_lines"

    id = Column(BigInteger, primary_key=True)
    line = Column(String, nullable=False, unique=True)

    production_records = relationship(
        "ProductionRecord", back_populates="production_line"
    )
    inspection_records = relationship(
        "InspectionRecord", back_populates="production_line"
    )


class Defect(Base):
    """Defect category.

    Attributes
    ----------
    id: int
    defect_code: str

    Relationships
    -------------
    inspection_records: list[InspectionRecord]
    """

    __tablename__ = "defects"

    id = Column(BigInteger, primary_key=True)
    defect_code = Column(String, nullable=False, unique=True)

    inspection_records = relationship(
        "InspectionRecord", back_populates="defect"
    )


class ProductionRecord(Base):
    """Production activity for a lot on a given date and line.

    Although the schema contains many fields like units_planned/actual, we only
    use the date and line information for summarization in this project.
    """

    __tablename__ = "production_records"

    id = Column(BigInteger, primary_key=True)
    lot_id = Column(BigInteger, ForeignKey("lots.id"), nullable=False)
    production_line_id = Column(
        BigInteger, ForeignKey("production_lines.id"), nullable=False
    )
    date = Column(Date, nullable=False)
    shift = Column(String, nullable=False)
    part_number = Column(String, nullable=False)
    units_planned = Column(Integer, nullable=False)
    units_actual = Column(Integer, nullable=False)
    downtime_min = Column(Integer, nullable=False)
    line_issue = Column(Boolean, nullable=False)
    primary_issue = Column(String, nullable=True)
    supervisor_notes = Column(String, nullable=True)

    lot = relationship("Lot", back_populates="production_records")
    production_line = relationship("ProductionLine", back_populates="production_records")


class InspectionRecord(Base):
    """Inspection finding for a lot, potentially with defects.

    The `qty_defects` / `defect_id` check constraint enforces the invariant
    that zero defect quantity implies no defect_id and vice versa.
    """

    __tablename__ = "inspection_records"

    id = Column(BigInteger, primary_key=True)
    lot_id = Column(BigInteger, ForeignKey("lots.id"), nullable=False)
    production_line_id = Column(
        BigInteger, ForeignKey("production_lines.id"), nullable=False
    )
    inspection_date = Column(Date, nullable=False)
    inspection_time = Column(Time, nullable=True)
    inspector = Column(String, nullable=False)
    part_number = Column(String, nullable=False)
    defect_id = Column(BigInteger, ForeignKey("defects.id"), nullable=True)
    defect_description = Column(String, nullable=True)
    severity = Column(String, nullable=True)
    qty_checked = Column(Integer, nullable=False)
    qty_defects = Column(Integer, nullable=False)
    disposition = Column(String, nullable=True)
    notes = Column(String, nullable=True)

    lot = relationship("Lot", back_populates="inspection_records")
    production_line = relationship("ProductionLine", back_populates="inspection_records")
    defect = relationship("Defect", back_populates="inspection_records")


class ShippingRecord(Base):
    """Shipment information for a lot.

    Only the ship_date and ship_status are required for the current user story,
    but we model the additional columns for completeness. A lot may have
    multiple shipments; queries should handle the latest status if needed.
    """

    __tablename__ = "shipping_records"

    id = Column(BigInteger, primary_key=True)
    lot_id = Column(BigInteger, ForeignKey("lots.id"), nullable=False)
    ship_date = Column(Date, nullable=False)
    sales_order_no = Column(String, nullable=False)
    customer = Column(String, nullable=False)
    destination_state = Column(String(2), nullable=False)
    carrier = Column(String, nullable=False)
    bol_no = Column(String, nullable=False, unique=True)
    tracking_pro = Column(String, nullable=True)
    qty_shipped = Column(Integer, nullable=False)
    ship_status = Column(String, nullable=False)
    hold_reason = Column(String, nullable=True)
    shipping_notes = Column(String, nullable=True)

    lot = relationship("Lot", back_populates="shipping_records")
